name: cache repo-report openssf score daily

on:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches:
      - 'actions'

jobs:
  openssf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Riyabelle25/repo-report-cache@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}